/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/404/': RouteRecordInfo<
      '/404/',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/datasource/': RouteRecordInfo<
      '/design/datasource/',
      '/design/datasource',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/echarts/': RouteRecordInfo<
      '/design/echarts/',
      '/design/echarts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/echarts/list': RouteRecordInfo<
      '/design/echarts/list',
      '/design/echarts/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/flow/': RouteRecordInfo<
      '/design/flow/',
      '/design/flow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/flow/list': RouteRecordInfo<
      '/design/flow/list',
      '/design/flow/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/form/': RouteRecordInfo<
      '/design/form/',
      '/design/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/form/form': RouteRecordInfo<
      '/design/form/form',
      '/design/form/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/form/list': RouteRecordInfo<
      '/design/form/list',
      '/design/form/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/list/': RouteRecordInfo<
      '/design/list/',
      '/design/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/list/content/[id]': RouteRecordInfo<
      '/design/list/content/[id]',
      '/design/list/content/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/design/list/list': RouteRecordInfo<
      '/design/list/list',
      '/design/list/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/screen/': RouteRecordInfo<
      '/design/screen/',
      '/design/screen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/screen/demo/map': RouteRecordInfo<
      '/design/screen/demo/map',
      '/design/screen/demo/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/screen/list': RouteRecordInfo<
      '/design/screen/list',
      '/design/screen/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/design/screen/show/[id]': RouteRecordInfo<
      '/design/screen/show/[id]',
      '/design/screen/show/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/docs/': RouteRecordInfo<
      '/docs/',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/api': RouteRecordInfo<
      '/docs/api',
      '/docs/api',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/form': RouteRecordInfo<
      '/docs/form',
      '/docs/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/form-option': RouteRecordInfo<
      '/docs/form-option',
      '/docs/form-option',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/list': RouteRecordInfo<
      '/docs/list',
      '/docs/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/list-option': RouteRecordInfo<
      '/docs/list-option',
      '/docs/list-option',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/screen': RouteRecordInfo<
      '/docs/screen',
      '/docs/screen',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/start': RouteRecordInfo<
      '/docs/start',
      '/docs/start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept': RouteRecordInfo<
      '/system/dept',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dict': RouteRecordInfo<
      '/system/dict',
      '/system/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/log': RouteRecordInfo<
      '/system/log',
      '/system/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu': RouteRecordInfo<
      '/system/menu',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/post': RouteRecordInfo<
      '/system/post',
      '/system/post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user': RouteRecordInfo<
      '/system/user',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/task/apply/': RouteRecordInfo<
      '/task/apply/',
      '/task/apply',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/task/apply/start': RouteRecordInfo<
      '/task/apply/start',
      '/task/apply/start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/task/applyed': RouteRecordInfo<
      '/task/applyed',
      '/task/applyed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/task/done': RouteRecordInfo<
      '/task/done',
      '/task/done',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/task/todo': RouteRecordInfo<
      '/task/todo',
      '/task/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test1': RouteRecordInfo<
      '/test1',
      '/test1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/upload': RouteRecordInfo<
      '/upload',
      '/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/404/index.vue': {
      routes:
        | '/404/'
      views:
        | never
    }
    'src/views/design/datasource/index.vue': {
      routes:
        | '/design/datasource/'
      views:
        | never
    }
    'src/views/design/echarts/index.vue': {
      routes:
        | '/design/echarts/'
      views:
        | never
    }
    'src/views/design/echarts/list.vue': {
      routes:
        | '/design/echarts/list'
      views:
        | never
    }
    'src/views/design/flow/index.vue': {
      routes:
        | '/design/flow/'
      views:
        | never
    }
    'src/views/design/flow/list.vue': {
      routes:
        | '/design/flow/list'
      views:
        | never
    }
    'src/views/design/form/index.vue': {
      routes:
        | '/design/form/'
      views:
        | never
    }
    'src/views/design/form/form.vue': {
      routes:
        | '/design/form/form'
      views:
        | never
    }
    'src/views/design/form/list.vue': {
      routes:
        | '/design/form/list'
      views:
        | never
    }
    'src/views/design/list/index.vue': {
      routes:
        | '/design/list/'
      views:
        | never
    }
    'src/views/design/list/content/[id].vue': {
      routes:
        | '/design/list/content/[id]'
      views:
        | never
    }
    'src/views/design/list/list.vue': {
      routes:
        | '/design/list/list'
      views:
        | never
    }
    'src/views/design/screen/index.vue': {
      routes:
        | '/design/screen/'
      views:
        | never
    }
    'src/views/design/screen/demo/map.vue': {
      routes:
        | '/design/screen/demo/map'
      views:
        | never
    }
    'src/views/design/screen/list.vue': {
      routes:
        | '/design/screen/list'
      views:
        | never
    }
    'src/views/design/screen/show/[id].vue': {
      routes:
        | '/design/screen/show/[id]'
      views:
        | never
    }
    'src/docs/index.md': {
      routes:
        | '/docs/'
      views:
        | never
    }
    'src/docs/api.md': {
      routes:
        | '/docs/api'
      views:
        | never
    }
    'src/docs/form.md': {
      routes:
        | '/docs/form'
      views:
        | never
    }
    'src/docs/form-option.md': {
      routes:
        | '/docs/form-option'
      views:
        | never
    }
    'src/docs/list.md': {
      routes:
        | '/docs/list'
      views:
        | never
    }
    'src/docs/list-option.md': {
      routes:
        | '/docs/list-option'
      views:
        | never
    }
    'src/docs/screen.md': {
      routes:
        | '/docs/screen'
      views:
        | never
    }
    'src/docs/start.md': {
      routes:
        | '/docs/start'
      views:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/views/system/dept.vue': {
      routes:
        | '/system/dept'
      views:
        | never
    }
    'src/views/system/dict.vue': {
      routes:
        | '/system/dict'
      views:
        | never
    }
    'src/views/system/log.vue': {
      routes:
        | '/system/log'
      views:
        | never
    }
    'src/views/system/menu.vue': {
      routes:
        | '/system/menu'
      views:
        | never
    }
    'src/views/system/post.vue': {
      routes:
        | '/system/post'
      views:
        | never
    }
    'src/views/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
    }
    'src/views/system/user.vue': {
      routes:
        | '/system/user'
      views:
        | never
    }
    'src/views/task/apply/index.vue': {
      routes:
        | '/task/apply/'
      views:
        | never
    }
    'src/views/task/apply/start.vue': {
      routes:
        | '/task/apply/start'
      views:
        | never
    }
    'src/views/task/applyed.vue': {
      routes:
        | '/task/applyed'
      views:
        | never
    }
    'src/views/task/done.vue': {
      routes:
        | '/task/done'
      views:
        | never
    }
    'src/views/task/todo.vue': {
      routes:
        | '/task/todo'
      views:
        | never
    }
    'src/views/test.vue': {
      routes:
        | '/test'
      views:
        | never
    }
    'src/views/test1.vue': {
      routes:
        | '/test1'
      views:
        | never
    }
    'src/views/upload.vue': {
      routes:
        | '/upload'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
