export default {
  dictSave: 'system/dict/save',
  dictList: 'system/dict/list',
  dictDelete: 'system/dict/delete',
  dictEdit: 'system/dict/edit',
  deptSave: 'system/dept/save',
  deptEdit: 'system/dept/edit',
  deptList: 'system/dept/list',
  deptDelete: 'system/dept/delete',
  menuSave: 'system/menu/save',
  menuEdit: 'system/menu/edit',
  menuList: 'system/menu/list',
  menuDelete: 'system/menu/delete',
  roleSave: 'system/role/save',
  roleEdit: 'system/role/edit',
  roleList: 'system/role/list',
  roleDelete: 'system/role/delete',
  userSave: 'system/user/save',
  userEdit: 'system/user/edit',
  userList: 'system/user/list',
  userDelete: 'system/user/delete'
}
